blank_issues_enabled: false
contact_links:
  - name: Questions & discussions
    url: https://github.com/yusuf-cirak/YC.EntityFrameworkCore.TigerData.TimescaleDB/discussions
    about: Ask "how do I…" questions or share ideas here instead of opening an issue.
