// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimescaleDb.Sample;

#nullable disable

namespace TimescaleDb.Sample.Migrations
{
    [DbContext(typeof(MetricsContext))]
    [Migration("20260613191040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("TimescaleDb:Jobs", "[{\"Name\":\"sample_noop_job\",\"Procedure\":\"public.sample_noop\",\"ScheduleInterval\":\"1 day\"}]");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimescaleDb.Sample.HourlyAverage", b =>
                {
                    b.Property<double>("Average")
                        .HasColumnType("double precision")
                        .HasColumnName("average");

                    b.Property<DateTime>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.ToTable((string)null);

                    b.ToView("hourly_averages", (string)null);

                    b
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:MaterializedOnly", true)
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:Query", "SELECT time_bucket(INTERVAL '1 hour', time) AS bucket,\n       device_id,\n       avg(value) AS average\nFROM readings\nGROUP BY 1, 2")
                        .HasAnnotation("TimescaleDb:ContinuousAggregate:WithNoData", true)
                        .HasAnnotation("TimescaleDb:IsContinuousAggregate", true)
                        .HasAnnotation("TimescaleDb:RefreshPolicy:EndOffset", "01:00:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:ScheduleInterval", "01:00:00")
                        .HasAnnotation("TimescaleDb:RefreshPolicy:StartOffset", "3 days");
                });

            modelBuilder.Entity("TimescaleDb.Sample.Reading", b =>
                {
                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.ToTable("readings", (string)null);

                    b
                        .HasAnnotation("TimescaleDb:Columnstore:Enabled", true)
                        .HasAnnotation("TimescaleDb:Columnstore:OrderBy", "time DESC")
                        .HasAnnotation("TimescaleDb:Columnstore:SegmentBy", "device_id")
                        .HasAnnotation("TimescaleDb:ColumnstorePolicy:After", "7 days")
                        .HasAnnotation("TimescaleDb:Hypertable:ChunkInterval", "1 day")
                        .HasAnnotation("TimescaleDb:Hypertable:PartitionColumn", "time")
                        .HasAnnotation("TimescaleDb:IsHypertable", true)
                        .HasAnnotation("TimescaleDb:RetentionPolicy:DropAfter", "90 days");
                });
#pragma warning restore 612, 618
        }
    }
}
