using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Npgsql.EntityFrameworkCore.PostgreSQL.Design.Internal;

namespace YC.EntityFrameworkCore.TigerData.TimescaleDB.Metadata;

/// <summary>
///     Converts the TimescaleDB annotations into Fluent API calls when scaffolding a
///     DbContext, and strips the <c>timescaledb.*</c> storage parameters that the model
///     finalizing convention regenerates from the semantic configuration.
/// </summary>
public class TimescaleDbAnnotationCodeGenerator : NpgsqlAnnotationCodeGenerator
{
    private static readonly MethodInfo IsHypertableMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.IsHypertable),
        [typeof(EntityTypeBuilder), typeof(string), typeof(string), typeof(bool?)]);

    private static readonly MethodInfo HasSpacePartitionMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.HasSpacePartition),
        [typeof(EntityTypeBuilder), typeof(string), typeof(int)]);

    private static readonly MethodInfo HasColumnstoreMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.HasColumnstore),
        [typeof(EntityTypeBuilder), typeof(string), typeof(string)]);

    private static readonly MethodInfo HasColumnstorePolicyMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.HasColumnstorePolicy),
        [typeof(EntityTypeBuilder), typeof(string), typeof(string)]);

    private static readonly MethodInfo HasRetentionPolicyMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.HasRetentionPolicy),
        [typeof(EntityTypeBuilder), typeof(string), typeof(string)]);

    private static readonly MethodInfo HasReorderPolicyMethod = GetMethod(
        nameof(TimescaleDbEntityTypeBuilderExtensions.HasReorderPolicy),
        [typeof(EntityTypeBuilder), typeof(string)]);

    public TimescaleDbAnnotationCodeGenerator(AnnotationCodeGeneratorDependencies dependencies)
        : base(dependencies)
    {
    }

    public override IReadOnlyList<MethodCallCodeFragment> GenerateFluentApiCalls(
        IEntityType entityType,
        IDictionary<string, IAnnotation> annotations)
    {
        var fragments = new List<MethodCallCodeFragment>(base.GenerateFluentApiCalls(entityType, annotations));

        if (Consume(annotations, TimescaleDbAnnotationNames.IsHypertable) is true)
        {
            var partitionColumn = (string?)Consume(annotations, TimescaleDbAnnotationNames.PartitionColumn);
            var chunkInterval = (string?)Consume(annotations, TimescaleDbAnnotationNames.ChunkInterval);
            var createDefaultIndexes = (bool?)Consume(annotations, TimescaleDbAnnotationNames.CreateDefaultIndexes);

            fragments.Add(createDefaultIndexes is null
                ? chunkInterval is null
                    ? new MethodCallCodeFragment(IsHypertableMethod, partitionColumn)
                    : new MethodCallCodeFragment(IsHypertableMethod, partitionColumn, chunkInterval)
                : new MethodCallCodeFragment(IsHypertableMethod, partitionColumn, chunkInterval, createDefaultIndexes));

            // Regenerated by the model finalizing convention.
            foreach (var name in annotations.Keys
                .Where(n => n.StartsWith("Npgsql:StorageParameter:timescaledb.", StringComparison.Ordinal))
                .ToList())
            {
                annotations.Remove(name);
            }
        }

        if (Consume(annotations, TimescaleDbAnnotationNames.SpacePartitionColumn) is string spaceColumn
            && Consume(annotations, TimescaleDbAnnotationNames.SpacePartitions) is int partitions)
        {
            fragments.Add(new MethodCallCodeFragment(HasSpacePartitionMethod, spaceColumn, partitions));
        }

        if (Consume(annotations, TimescaleDbAnnotationNames.ColumnstoreEnabled) is true)
        {
            fragments.Add(new MethodCallCodeFragment(
                HasColumnstoreMethod,
                Consume(annotations, TimescaleDbAnnotationNames.ColumnstoreSegmentBy),
                Consume(annotations, TimescaleDbAnnotationNames.ColumnstoreOrderBy)));
        }

        if (Consume(annotations, TimescaleDbAnnotationNames.ColumnstorePolicyAfter) is string after)
        {
            fragments.Add(MethodWithOptionalSecondArgument(
                HasColumnstorePolicyMethod, after,
                Consume(annotations, TimescaleDbAnnotationNames.ColumnstorePolicyScheduleInterval)));
        }

        if (Consume(annotations, TimescaleDbAnnotationNames.RetentionPolicyDropAfter) is string dropAfter)
        {
            fragments.Add(MethodWithOptionalSecondArgument(
                HasRetentionPolicyMethod, dropAfter,
                Consume(annotations, TimescaleDbAnnotationNames.RetentionPolicyScheduleInterval)));
        }

        if (Consume(annotations, TimescaleDbAnnotationNames.ReorderPolicyIndex) is string index)
        {
            fragments.Add(new MethodCallCodeFragment(HasReorderPolicyMethod, index));
        }

        return fragments;
    }

    private static MethodCallCodeFragment MethodWithOptionalSecondArgument(
        MethodInfo method,
        string first,
        object? second)
        => second is null
            ? new MethodCallCodeFragment(method, first)
            : new MethodCallCodeFragment(method, first, second);

    private static object? Consume(IDictionary<string, IAnnotation> annotations, string name)
    {
        if (annotations.TryGetValue(name, out var annotation))
        {
            annotations.Remove(name);
            return annotation.Value;
        }

        return null;
    }

    private static MethodInfo GetMethod(string name, Type[] parameterTypes)
        => typeof(TimescaleDbEntityTypeBuilderExtensions).GetMethod(name, parameterTypes)
            ?? throw new InvalidOperationException($"Method '{name}' not found.");
}
